export enum RoutePath {
  Root = "/",
  Explore = "/explore",
  CreateWallet = "/create",
  RestoreWallet = "/restore",
  Balances = "/balances",
  Mnemonic = "/mnemonic",
  Password = "/password",
  Send = "/send",
  Addresses = "/addresses",
  ConfirmTransaction = "/confirm-transaction",
  ConnectWallet = "/connect-wallet",
  SendBTC = "/send-btc",
  Settings = "/settings",
  SwitchNetwork = "/switch-network",
  DecodeAndSignPsbt = "/decode-and-sign-psbt",
  SignMessage = "/sign-message",
  VerifySign = "/verify-message",
}
