name: Build and Release

on:
#  push:
#    tags:
#      - 'v*'
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'current'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    - name: Package /dist directory
      run: zip -r dist.zip dist/

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist.zip
        tag: "test"
        allowUpdates: true
        artifactContentType: application/zip

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist.zip
        tag_name: "test"
